# ----------------- FOR TESTING ONLY -----------------
# - THESE SETTINGS SHOULD BE REVIEWED FOR PRODUCTION -
# -https://www.elastic.co/guide/en/elasticsearch/reference/6.7/important-settings.html - 
http.port: 9200

# for the elasticsearch-head plugin
http.cors.enabled: true
http.cors.allow-origin: "*"
